export const ACTIVATE_POPUP = 'ACTIVATE_POPUP'
export const DEACTIVATE_POPUP = 'DEACTIVATE_POPUP'

export const GET_SCHEDULE_FETCH_START = 'GET_SCHEDULE_FETCH_START'
export const GET_SCHEDULE_FETCH_SUCCESS = 'GET_SCHEDULE_FETCH_SUCCESS'
export const GET_SCHEDULE_FETCH_ERROR = 'GET_SCHEDULE_FETCH_ERROR'

export const RENT_INTERVAL_FETCH_START = 'RENT_INTERVAL_FETCH_START'
export const RENT_INTERVAL_FETCH_SUCCESS = 'RENT_INTERVAL_FETCH_SUCCESS'
export const RENT_INTERVAL_FETCH_ERROR = 'RENT_INTERVAL_FETCH_ERROR'

export const GET_INSTRUCTORS_FETCH_START = 'GET_INSTRUCTORS_FETCH_START'
export const GET_INSTRUCTORS_FETCH_SUCCESS = 'GET_INSTRUCTORS_FETCH_SUCCESS'
export const GET_INSTRUCTORS_FETCH_ERROR = 'GET_INSTRUCTORS_FETCH_ERROR'

export const GET_PRACTICE_MODES_FETCH_START = 'GET_PRACTICE_MODES_FETCH_START'
export const GET_PRACTICE_MODES_FETCH_SUCCESS =
  'GET_PRACTICE_MODES_FETCH_SUCCESS'
export const GET_PRACTICE_MODES_FETCH_ERROR = 'GET_PRACTICE_MODES_FETCH_ERROR'

export const CHANGE_PRACTICE_MODE = 'CHANGE_PRACTICE_MODE'
export const CHANGE_INSTRUCTOR = 'CHANGE_INSTRUCTOR'

export const GET_PERSONAL_FETCH_START = 'GET_PERSONAL_FETCH_START'
export const GET_PERSONAL_FETCH_SUCCESS = 'GET_PERSONAL_FETCH_SUCCESS'
export const GET_PERSONAL_FETCH_ERROR = 'GET_PERSONAL_FETCH_ERROR'

export const GET_PERSON_SCHEDULE_FETCH_START = 'GET_PERSON_SCHEDULE_FETCH_START'
export const GET_PERSON_SCHEDULE_FETCH_SUCCESS =
  'GET_PERSON_SCHEDULE_FETCH_SUCCESS'
export const GET_PERSON_SCHEDULE_FETCH_ERROR = 'GET_PERSON_SCHEDULE_FETCH_ERROR'

export const GET_PERSONAL_MODES_FETCH_START = 'GET_PERSONAL_MODES_FETCH_START'
export const GET_PERSONAL_MODES_FETCH_SUCCESS =
  'GET_PERSONAL_MODES_FETCH_SUCCESS'
export const GET_PERSONAL_MODES_FETCH_ERROR = 'GET_PERSONAL_MODES_FETCH_ERROR'

export const CHANGE_PERSONAL_MODE = 'CHANGE_PERSONAL_MODE'

export const ADD_NEW_USER_FETCH_START = 'ADD_USER_FETCH_START'
export const ADD_NEW_USER_FETCH_SUCCESS = 'ADD_USER_FETCH_SUCCESS'
export const ADD_NEW_USER_FETCH_ERROR = 'ADD_USER_FETCH_ERROR'

export const GET_ROLES_FETCH_START = 'GET_ROLES_FETCH_START'
export const GET_ROLES_FETCH_SUCCESS = 'GET_ROLES_FETCH_SUCCESS'
export const GET_ROLES_FETCH_ERROR = 'GET_ROLES_FETCH_ERROR'

export const GET_ALL_USERS_FETCH_START = 'GET_ALL_USERS_FETCH_START'
export const GET_ALL_USERS_FETCH_SUCCESS = 'GET_ALL_USERS_FETCH_SUCCESS'
export const GET_ALL_USERS_FETCH_ERROR = 'GET_ALL_USERS_FETCH_ERROR'

export const FILTER_USERS = 'FILTER_USERS'

export const GET_SETTINGS_SCHEDULE_FETCH_START =
  'GET_SETTINGS_SCHEDULE_FETCH_START'
export const GET_SETTINGS_SCHEDULE_FETCH_SUCCESS =
  'GET_SETTINGS_SCHEDULE_FETCH_SUCCESS'
export const GET_SETTINGS_SCHEDULE_FETCH_ERROR =
  'GET_SETTINGS_SCHEDULE_FETCH_ERROR'

export const SET_SETTINGS_SCHEDULE = 'SET_SETTINGS_SCHEDULE'
export const SET_SETTINGS_CHANGED_CELLS = 'SET_SETTINGS_CHANGED_CELLS'

export const CHANGE_SETTINGS_SCHEDULE_MODE = 'CHANGE_SETTINGS_SCHEDULE_MODE'

export const SET_SETTINGS_SCHEDULE_FETCH_START =
  'SET_SETTINGS_SCHEDULE_FETCH_START'
export const SET_SETTINGS_SCHEDULE_FETCH_SUCCESS =
  'SET_SETTINGS_SCHEDULE_FETCH_SUCCESS'
export const SET_SETTINGS_SCHEDULE_FETCH_ERROR =
  'SET_SETTINGS_SCHEDULE_FETCH_ERROR'

export const GET_VARIABLES_FETCH_START = 'GET_VARIABLES_FETCH_START'
export const GET_VARIABLES_FETCH_SUCCESS = 'GET_VARIABLES_FETCH_SUCCESS'
export const GET_VARIABLES_FETCH_ERROR = 'GET_VARIABLES_FETCH_ERROR'
